### ISSUE TITLE
Bridge Issue: Can't Unwrap

### ISSUE THREAD

**Issue by omniwired** [neutron-org/neutron#330]
How to reproduce:

https://bridge.neutron.org/canonize 

Try to unwrap

Check the chrome console, "can't fetch config".

**Comment by oldremez** [comment]
Hey, sorry for the inconvenience, it was an RPC accessibility issue.
For user-related bug reports that aren't related to the code itself but for deployments/UX and so on please use the community chat: https://t.me/neutron_community. There you can get a much faster response.

**Comment by oldremez** [comment]
Closing
1. issue is resolved
2. issue is unrelated to the Neutron core
