### ISSUE TITLE
docs: how to run local devnet

### ISSUE THREAD

**Issue by dzmitry-lahoda** [neutron-org/neutron#407]
still have the issue https://t.me/c/1930030171/133

**Comment by dzmitry-lahoda** [comment]
at least - is it related to CCV consumer https://github.com/neutron-org/neutron/blob/fee60f7azf8694749172b3d99c66882d5fb80f3/app/ccv_msg_filter_add.go 

? 

i mean can I run it with cosmos hub instead? it does not seems init sh scripts setup consumer chains

**Comment by reecepbcups** [comment]
@dzmitry-lahoda Run it with local-interchain: https://github.com/strangelove-ventures/interchaintest/blob/main/local-interchain/chains/interchainsecurity.json

here is a config which auto runs your relayers, cosmoshub, and neutron instance. There is a patch coming soon which also has stride included too -> https://github.com/strangelove-ventures/interchaintest/pull/1235
