### ISSUE TITLE
Stuck on random blocks in V3.0.4

### ISSUE THREAD

**Issue by i-m-alexander** [neutron-org/neutron#488]
After update from v3.0.2 to v3.0.4, nodes stuck randomly on some blocks. In journal only errors about fee estimate and peers connect error. The only way to resolve, is start from Polkachu snapshot on v3.0.2.
Any help would be great!

**Comment by pr0n00gler** [comment]
You are talking about testnet or mainnet?

**Comment by i-m-alexander** [comment]
Node and validator running on mainnet.

**Comment by pr0n00gler** [comment]
Mainnet upgrade to v3.0.4 didn't happen yet, so you should use v3.0.2 on mainnet and wait for further announcement to upgrade to v3.0.4

The testnet upgrade will happen only on block 13,815,000, you can see upgrade notes here: https://github.com/cosmos/testnets/blob/master/interchain-security/pion-1/v3.0.4_upgrade.md
