### ISSUE TITLE
no pre-release containers

### ISSUE THREAD

**Issue by bert2002** [neutron-org/neutron#575]
Hi,
it seems that no pre-release's have docker images build and pushed. At the moment we cant run testnet, because of this, e.g. releases for [v4.0.0-rc2](https://github.com/neutron-org/neutron/releases/tag/v4.0.0-rc2) or `rc1`.

Thanks,
bert

**Comment by pr0n00gler** [comment]
Looking into that

**Comment by keylogic1** [comment]
@bert2002 Please find the latest docker image available [here](https://hub.docker.com/layers/neutronorg/neutron/v4.0.0-rc2/images/sha256-9c6c7456ddeae1d22061f409c2881185460b69e4b32489bf6133bd57f00b580c?context=repo)

**Comment by bert2002** [comment]
Hi @keylogic1 it happened again for `neutronorg/neutron:v4.0.1-testnet` :)

**Comment by bert2002** [comment]
Created a pull request which should fix this: https://github.com/neutron-org/neutron/pull/603
