### ISSUE TITLE
Doesn't start as per official documentation like most tendermint/cosmos-like software

### ISSUE THREAD

**Issue by visualbasic6** [neutron-org/neutron#608]
`bash contrib/statesync.bash` doesn't work - it just throws tendermint errors. learn how to program. i'm not going to pen test this for immunefi because i'm so turned off by this ineptitude. you guys received funding? i hope not. fix this if you want to be taken seriously in this seedy "industry" lmao

fix it

**Comment by zavgorodnii** [comment]
Hey @visualbasic6,

Thank you for bringing this to our attention. We appreciate your feedback.

We identified an issue with the script and have already fixed it. Please feel free to test the script once again. If you encounter any further issues or have additional feedback, do not hesitate to reach out.

Thank you for your understanding and cooperation.
