### ISSUE TITLE
API returns expected 2 wire type, got 0: tx parse error

### ISSUE THREAD

**Issue by jack-dot-wu** [neutron-org/neutron#627]
I use the api '/cosmos/tx/v1beta1/txs?events=tx.height=12403840&pagination.offset=0&pagination.limit=100' to curl the node, but the node return 'query cannot be empty', I find it 'events is the list of transaction event type.
Deprecated post v0.47.x: use query instead, which should contain a valid
events query.' So i change the api '/cosmos/tx/v1beta1/txs?query=tx.height=12403840&pagination.offset=0&pagination.limit=100', but it return 'expected 2 wire type, got 0: tx parse error'. How to query the bloclk info  with the api?

**Comment by pr0n00gler** [comment]
What RPC are you using?
