### ISSUE TITLE
tx query api DO NOT return logs any more

### ISSUE THREAD

**Issue by wooyeeyii** [neutron-org/neutron#649]
```
curl 'https://api.neutron.quokkastake.io/cosmos/tx/v1beta1/txs/83EF94B202800313ECE7C2206CFB778895FE42236587F3BC11FB13CFA041711C'
```
returned with empty slice of logs

**Comment by pr0n00gler** [comment]
The field logs is not populated anymore in Cosmos SDK 0.50+ to avoid duplication

https://github.com/cosmos/cosmos-sdk/pull/15845
