### ISSUE TITLE
The golang:v1.22-alpine3.18 image uses golang v1.22.3

### ISSUE THREAD

**Issue by diesel-dunamu** [neutron-org/neutron#688]
The `golang:v1.22-alpine3.18` image uses golang `v1.22.3` . The `Dockerfile.builder` of version `v4.2.1` fails to build.
https://github.com/neutron-org/neutron/blob/ac620c19ae88c9d8697190664f709931f33b007d/Dockerfile.builder#L10
<img width="643" alt="스크린샷 2024-08-22 오전 1 10 15" src="https://github.com/user-attachments/assets/1f901a4e-f039-4a96-9c1f-26ed89bcd112">

**Comment by pr0n00gler** [comment]
It uses go toolchain v1.22.6 inside https://github.com/neutron-org/neutron/blob/ac620c19ae88c9d8697190664f709931f33b007d/Dockerfile.builder#L17

And `make build-static-linux-amd64` command works as expected

**Comment by diesel-dunamu** [comment]
I confirmed it. Thank you.
